version: "3.8"

services:
  bz-sentinel:
    build:
      context: .
    image: bz-sentinel:0.1.10
    container_name: bz-sentinel
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - bzf
    volumes:
      - /var/data/bz-sentinel:/data
    labels:
      - "type=app"
    command: [ "/app/src/main.py" ]

networks:
  bzf:
    external: true
