services:
  bz-sentinel:
    build:
      context: .
    image: bz-sentinel:0.1.16
    container_name: bz-sentinel
    restart: unless-stopped
    networks:
      - int
    env_file:
      - .env
    volumes:
      - /var/data/bz-sentinel:/data
    labels:
      - "tainn.type=app"
    entrypoint: [ "uv", "run", "/app/src/main.py" ]

networks:
  int:
    external: true
