version: "3.8"

services:
  bz-sentinel:
    build:
      context: .
    image: bz-sentinel:0.1.12
    container_name: bz-sentinel
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - bzf
    volumes:
      - /var/data/bz-sentinel:/data
    labels:
      - "app"
    command: [ "python3", "/app/src/main.py" ]

networks:
  bzflag:
    name: bzflag
    driver: bridge
