services:
  bz-sentinel:
    build:
      context: .
    image: bz-sentinel:0.1.13
    container_name: bz-sentinel
    restart: unless-stopped
    networks:
      - bzflag
    env_file:
      - .env
    volumes:
      - /var/data/bz-sentinel:/data
    labels:
      - "type=app"
    command: [ "uv", "run", "/app/src/main.py" ]

networks:
  bzflag:
    name: bzflag
    driver: bridge
