services:
  bz-sentinel:
    build:
      context: .
    image: bz-sentinel:0.1.14
    container_name: bz-sentinel
    restart: unless-stopped
    networks:
      - ffa
    env_file:
      - .env
    volumes:
      - /var/data/bz-sentinel:/data
    labels:
      - "type=app"
    command: [ "uv", "run", "/app/src/main.py" ]

networks:
  ffa:
    external: true
